// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `playlist_tracks` table.
    ///
    /// (Automatically generated by Diesel.)
    playlist_tracks (playlist_id, track_number) {
        /// The `playlist_id` column of the `playlist_tracks` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        playlist_id -> Integer,
        /// The `track_id` column of the `playlist_tracks` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        track_id -> Integer,
        /// The `track_number` column of the `playlist_tracks` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        track_number -> Integer,
    }
}

diesel::table! {
    /// Representation of the `playlists` table.
    ///
    /// (Automatically generated by Diesel.)
    playlists (id) {
        /// The `id` column of the `playlists` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `name` column of the `playlists` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `description` column of the `playlists` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
        /// The `image_path` column of the `playlists` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        image_path -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `tracks` table.
    ///
    /// (Automatically generated by Diesel.)
    tracks (local_id) {
        /// The `local_id` column of the `tracks` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        local_id -> Integer,
        /// The `title` column of the `tracks` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        title -> Text,
        /// The `artist` column of the `tracks` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        artist -> Nullable<Text>,
        /// The `album` column of the `tracks` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        album -> Nullable<Text>,
        /// The `album_artist` column of the `tracks` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        album_artist -> Nullable<Text>,
        /// The `track_number` column of the `tracks` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        track_number -> Nullable<Integer>,
        /// The `genre` column of the `tracks` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        genre -> Nullable<Text>,
        /// The `composer` column of the `tracks` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        composer -> Nullable<Text>,
        /// The `length` column of the `tracks` table.
        ///
        /// Its SQL type is `Float`.
        ///
        /// (Automatically generated by Diesel.)
        length -> Float,
        /// The `sample_rate` column of the `tracks` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        sample_rate -> Integer,
        /// The `codec` column of the `tracks` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        codec -> Text,
        /// The `filepath` column of the `tracks` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        filepath -> Text,
    }
}

diesel::joinable!(playlist_tracks -> playlists (playlist_id));

diesel::allow_tables_to_appear_in_same_query!(
    playlist_tracks,
    playlists,
    tracks,
);
